worker_processes auto;
pid /var/run/nginx.pid;
error_log /var/log/nginx/error.log warn;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 1024;
}

stream {
    log_format panel_stream '$time_iso8601\t$server_port\t$bytes_sent\t$bytes_received';
    access_log /var/log/nginx/stream-access.log panel_stream;

    include /etc/nginx/streams-enabled/*.conf;
}
